import { defineConfig, devices } from "@playwright/test";
import { resolve } from "node:path";

const APP_PORT = Number(process.env.E2E_APP_PORT ?? 3100);
export const BASE_URL = `http://127.0.0.1:${APP_PORT}`;
export const TRELLO_STUB = `http://127.0.0.1:${process.env.E2E_TRELLO_PORT ?? 4100}`;

// Playwright loads this config as CommonJS, so no import.meta here; it runs
// from the project root.
const fixture = resolve("fixtures/tasks.y4m");

export default defineConfig({
  testDir: "./tests/e2e",
  testMatch: "**/*.spec.ts",
  // OCR runs for real in the browser, and the first run downloads its language
  // data, so these are not fast tests.
  timeout: 120_000,
  expect: { timeout: 20_000 },
  // One fake-Trello holds the state every spec reads, so they take turns.
  fullyParallel: false,
  workers: 1,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? "list" : [["list"], ["html", { open: "never" }]],

  use: {
    baseURL: BASE_URL,
    trace: "retain-on-failure",
    permissions: ["camera"],
    launchOptions: {
      args: [
        "--use-fake-device-for-media-stream",
        "--use-fake-ui-for-media-stream",
        // y4m is the only format Chrome's fake capture accepts; the file is
        // generated by tests/e2e/make-fixture.mjs.
        `--use-file-for-fake-video-capture=${fixture}`,
      ],
    },
  },

  projects: [
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
    {
      name: "mobile",
      use: {
        ...devices["Desktop Chrome"],
        // A phone, but still Chromium — WebKit cannot take the fake-camera
        // flags the capture flow needs.
        viewport: { width: 390, height: 844 },
        isMobile: true,
        hasTouch: true,
        deviceScaleFactor: 3,
      },
    },
  ],

  webServer: {
    // Boots an in-memory Mongo and the fake Trello, then `next start` against
    // both. See tests/e2e/server.mjs.
    command: "node tests/e2e/server.mjs",
    url: `${BASE_URL}/login`,
    reuseExistingServer: !process.env.CI,
    timeout: 240_000,
    stdout: "pipe",
  },
});
